[[projects]]
name = "@redis/client"
tarballs = "./tarballs"
packages = [
  { name = "@redis/client", version = "1.0.6" },
  { name = "cluster-key-slot", version = "1.1.2" },
  { name = "yallist", version = "4.0.0" },
  { name = "generic-pool", version = "3.8.2" },
]
vuln = [
  { package = "generic-pool", module = "lib/Pool.js", row = 743, column = 17 }
]

[[projects]]
name = "path-scurry"
tarballs = "./tarballs"
packages = [
  { name = "path-scurry", version = "1.6.1" },
  { name = "lru-cache", version = "7.14.1" },
  { name = "minipass", version = "4.0.2" },
]
vuln = [
  { package = "lru-cache", module = "index.js", row = 1017, column = 24 }
]
