---
name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchains
        run: |
          rustup toolchain install stable --profile minimal -c clippy
          rustup toolchain install nightly --profile minimal -c rustfmt
          rustup default stable

      - name: Format check
        run: cargo +nightly fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Oldstable
        run: |
          oldstable=$(cat "./vuln-reach/Cargo.toml" | grep "rust-version" | sed 's/.*"\(.*\)".*/\1/')
          rustup toolchain install --profile minimal "$oldstable"
          cargo "+$oldstable" check

      - name: Tests
        run: cargo test
